export const VERSION_HISTORY = [
  {
    version: "0.1.13",
    date: "2026-08-26",
    title: "Emergency Hotfix 1",
    features: [
      {
        type: "bugfix",
        title: "Crash Fix",
        description: "A recent DeepSeek update caused the extension to break. We have prepared an emergency fix to restore critical extension functionality. We are closely monitoring the situation and will release further hotfixes if needed."
      },
      {
        type: "feature",
        title: "Search Provider List",
        description: "Configure and prioritize your preferred search engines (Bing, DuckDuckGo Lite, DuckDuckGo HTML) directly in settings."
      }
    ]
  },
  {
    version: "0.1.12",
    date: "2026-08-15",
    title: "DeepCode, Queued Prompts & Stability",
    features: [
      {
        type: "developer",
        title: "DeepCode (Experimental)",
        description: "Collaborative coding mode powered by DeepSeek Harness. Plan tasks in DeepSeek and send them directly to Harness using the <a href='https://github.com/EdgeTypE/dsh-better-deepseek' target='_blank' style='color: #4d6bfe; text-decoration: underline;'>dsh-better-deepseek</a> plugin."
      },
      {
        type: "feature",
        title: "Queued Prompts",
        description: "Send messages while DeepSeek is generating responses. BDS queues them and submits them automatically once generation completes."
      },
      {
        type: "bugfix",
        title: "Stability & UX Improvements",
        description: "Tool parser fixes for DeepSeek UI updates, export support for created skills/personas, legacy card cleanup, and Android search improvements."
      }
    ]
  },
  {
    version: "0.1.11",
    date: "2026-07-27",
    title: "MCP Servers, Dynamic Tables & Stability",
    features: [
      {
        type: "feature",
        title: "MCP Server Support",
        description: "Connect remote MCP servers to DeepSeek for external tool access. Configure servers in Settings → Advanced Settings → MCP Servers."
      },
      {
        type: "feature",
        title: "Dynamic Tables",
        description: "Sort data and reorder columns directly in tables generated by DeepSeek."
      },
      {
        type: "bugfix",
        title: "Stability & UX Improvements",
        description: "Dozens of bug fixes and UI/UX improvements across the extension."
      }
    ]
  },
  {
    version: "0.1.10",
    date: "2026-06-30",
    title: "Stability & Improvement",
    features: [
      {
        type: "feature",
        title: "Image Support",
        description: "DeepSeek can now search and display images from Wikimedia Commons directly in the conversation with the new BDS:IMAGE tag."
      },
      {
        type: "feature",
        title: "Slash-Command System",
        description: "A full slash-command subsystem with autocomplete, context hand-off, built-in commands, and the ability to create custom commands from saved snippets."
      },
      {
        type: "bugfix",
        title: "Bug Fixes & UX Improvements",
        description: "Numerous bug fixes and UX refinements across the extension."
      }
    ]
  },
  {
    version: "0.1.9",
    date: "2026-06-13",
    title: "Multi-System Prompts, Visualizer Rework & Deep Research",
    features: [
      {
        type: "feature",
        title: "Multi-System Prompt Mode & Advanced Scheduling",
        description: "Use multiple system prompt entries with per-entry scheduling options - first message, every N turns, or always."
      },
      {
        type: "feature",
        title: "Visualizer Rework",
        description: "Visualizer widgets can now be resized and downloaded. The entire UI has been reworked for a cleaner experience."
      },
      {
        type: "feature",
        title: "DeepResearch",
        description: "Tell DeepSeek a topic, review the generated plan, and upon approval it conducts deep multi-step research automatically."
      },
      {
        type: "export",
        title: "Export/Import Overhaul",
        description: "All extension data (settings, skills, memories, characters, projects) can now be exported and imported with optional encryption support."
      }
    ]
  },
  {
    version: "0.1.8",
    date: "2026-06-01",
    title: "Memory Rework, Saved Items & API Playground",
    features: [
      {
        type: "feature",
        title: "Memory Rework",
        description: "Called memory system has been reworked with a token overlap-based approach for better context matching."
      },
      {
        type: "feature",
        title: "Saved Items (Bookmarks & Snippets)",
        description: "Save messages for later access. Create snippets and send them with a single click."
      },
      {
        type: "feature",
        title: "Skill Creator Tool",
        description: "Ask AI to create a custom skill for you directly from the chat."
      },
      {
        type: "feature",
        title: "Import Memory from Another AI",
        description: "Import your memory from other AI platforms into DeepSeek."
      },
      {
        type: "developer",
        title: "API Playground",
        description: "A built-in playground to easily test the DeepSeek API."
      },
      {
        type: "feature",
        title: "Auto Search Tool",
        description: "Replaced the removed Expert mode link reading and search with our own integrated search tool."
      },
      {
        type: "bugfix",
        title: "Bug Fixes & UX Improvements",
        description: "Numerous bug fixes and UX refinements across the extension."
      }
    ]
  },
  {
    version: "0.1.7",
    date: "2026-05-22",
    title: "Localization, Custom Prompts & RAG",
    features: [
      {
        type: "feature",
        title: "Localization System",
        description: "Better DeepSeek now supports multiple languages. Help us improve translations or add your language on <a href='https://github.com/EdgeTypE/better-deepseek' target='_blank' style='color: #4d6bfe; text-decoration: underline;'>GitHub</a>."
      },
      {
        type: "feature",
        title: "Custom Prompts",
        description: "Create, save, and switch between multiple system prompts effortlessly."
      },
      {
        type: "feature",
        title: "Project RAG Search",
        description: "A primitive RAG system has been added. Connect a project or select a local folder for file search. We'll continue improving this in future releases."
      },
      {
        type: "feature",
        title: "UI Improvements",
        description: "Collapse/expand for long messages, extension icon opens DeepSeek website, renderable cards for fetch operations, server status and announcement banners."
      },
      {
        type: "bugfix",
        title: "Bug Fixes & Performance",
        description: "BDS tool parser and Office tool improvements. Fixed font rendering issues. Various stability and performance optimizations."
      }
    ]
  },
  {
    version: "0.1.6",
    date: "2026-05-12",
    title: "Android & Organization",
    features: [
      {
        type: "platform",
        title: "Android Version",
        description: "Better DeepSeek is now available on <a href='https://github.com/EdgeTypE/better-deepseek/releases' target='_blank' style='color: #4d6bfe; text-decoration: underline;'>Android</a>."
      },
      {
        type: "organization",
        title: "Chat Filtering & Tags",
        description: "Organize your sessions by adding tags. Filter and group chats easily from the sidebar menu."
      },
      {
        type: "export",
        title: "Export UI Rework",
        description: "Newly designed export interface for Markdown, PDF, HTML, and Images. Export full sessions or specific parts."
      }
    ]
  },
  {
    version: "0.1.5",
    date: "2026-05-06",
    title: "Refinement & Visibility",
    features: [
      {
        type: "feature",
        title: "What's New Popup",
        description: "You're looking at it! We'll now keep you updated on the latest changes right here."
      },
      {
        type: "feature",
        title: "Advanced Injection Control",
        description: "Choose between 'Always', 'First Message', or 'Every X' messages with customizable intervals for system prompts."
      },
      {
        type: "feature",
        title: "Private Repo Support",
        description: "Import private repositories via GitHub Personal Access Tokens securely."
      },
      {
        type: "feature",
        title: "Token & Price Estimation",
        description: "Real-time token usage estimation and context window display for API-equivalent usage."
      },
      {
        type: "settings",
        title: "Disable Memory",
        description: "New toggle in Settings to prevent the extension from persisting conversation context."
      },
      {
        type: "bugfix",
        title: "Stability Improvements",
        description: "Resolved issues with message handling and refined the overall UI state."
      }
    ]
  },
  {
    version: "0.1.4",
    date: "2026-04-30",
    title: "Projects & Advanced Settings",
    features: [
      {
        type: "organization",
        title: "Projects Menu",
        description: "Better organizational control for sessions and files."
      },
      {
        type: "search",
        title: "History Search",
        description: "Added search functionality to the session history sidebar."
      },
      {
        type: "settings",
        title: "Advanced Settings",
        description: "Reworked settings menu with an accordion layout to save space and improve focus."
      },
      {
        type: "settings",
        title: "Disable System Prompt",
        description: "New option to disable the Hidden System Prompt entirely when not needed."
      },
      {
        type: "settings",
        title: "Force Language",
        description: "Ensure DeepSeek always responds in your preferred language, regardless of input."
      }
    ]
  },
  {
    version: "0.1.3",
    date: "2026-04-28",
    title: "Ask Questions & Exports",
    features: [
      {
        type: "interactive",
        title: "Ask Questions Tool",
        description: "DeepSeek can now ask for clarification when unsure about context or instructions."
      },
      {
        type: "export",
        title: "Markdown & PDF Export",
        description: "Export your full chat sessions to Markdown and PDF files."
      },
      {
        type: "settings",
        title: "Prompt Reset",
        description: "Easily reset the system prompt to its default state."
      },
      {
        type: "bugfix",
        title: "Navigation Fixes",
        description: "Resolved full page reloading issues when clicking the logo or 'New Chat'."
      }
    ]
  },
  {
    version: "0.1.2",
    date: "2026-04-23",
    title: "Cross-Browser & Code Runners",
    features: [
      {
        type: "crossplatform",
        title: "Firefox Support",
        description: "Added experimental support for the Firefox browser."
      },
      {
        type: "developer",
        title: "Enhanced Code Runners",
        description: "Updated Python runner and added new JS and TS execution environments."
      },
      {
        type: "developer",
        title: "GitHub Auto-Fetch",
        description: "Inject GitHub repositories directly into the chat via the BDS:AUTO command."
      }
    ]
  },
  {
    version: "0.1.1",
    date: "2026-04-18",
    title: "Voice Support & Reliability",
    features: [
      {
        type: "voice",
        title: "Full Voice Support",
        description: "Complete Speech-to-Text and Text-to-Speech integration."
      },
      {
        type: "settings",
        title: "Voice Configuration",
        description: "Configurable voice and recognition languages available in Settings."
      },
      {
        type: "feature",
        title: "Improved Navigation",
        description: "Logo and 'New Chat' are now real <a> tags, supporting 'Open in new tab'."
      },
      {
        type: "performance",
        title: "Streaming Reliability",
        description: "Better handling of stalled streams and automatic closing of tags."
      }
    ]
  }
];

export const LATEST_VERSION = VERSION_HISTORY[0];

